// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthServiceError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ErrCode        int64                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrDescription string                 `protobuf:"bytes,2,opt,name=err_description,json=errDescription,proto3" json:"err_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthServiceError) Reset() {
	*x = AuthServiceError{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthServiceError) ProtoMessage() {}

func (x *AuthServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthServiceError.ProtoReflect.Descriptor instead.
func (*AuthServiceError) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthServiceError) GetErrCode() int64 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *AuthServiceError) GetErrDescription() string {
	if x != nil {
		return x.ErrDescription
	}
	return ""
}

type LoginCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCustomerRequest) Reset() {
	*x = LoginCustomerRequest{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCustomerRequest) ProtoMessage() {}

func (x *LoginCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCustomerRequest.ProtoReflect.Descriptor instead.
func (*LoginCustomerRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type LoginCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCustomerResponse) Reset() {
	*x = LoginCustomerResponse{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCustomerResponse) ProtoMessage() {}

func (x *LoginCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCustomerResponse.ProtoReflect.Descriptor instead.
func (*LoginCustomerResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginCustomerResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LoginCustomerResponse) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type SendOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpRequest) Reset() {
	*x = SendOtpRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpRequest) ProtoMessage() {}

func (x *SendOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpRequest.ProtoReflect.Descriptor instead.
func (*SendOtpRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SendOtpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SendOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expiration    int32                  `protobuf:"varint,1,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
	TotalSent     int32                  `protobuf:"varint,2,opt,name=TotalSent,proto3" json:"TotalSent,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpResponse) Reset() {
	*x = SendOtpResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpResponse) ProtoMessage() {}

func (x *SendOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpResponse.ProtoReflect.Descriptor instead.
func (*SendOtpResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SendOtpResponse) GetExpiration() int32 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *SendOtpResponse) GetTotalSent() int32 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *SendOtpResponse) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ConfirmOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           string                 `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // IP клиента (если нужно фиксировать)
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"` // User-Agent клиента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOtpRequest) Reset() {
	*x = ConfirmOtpRequest{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOtpRequest) ProtoMessage() {}

func (x *ConfirmOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOtpRequest.ProtoReflect.Descriptor instead.
func (*ConfirmOtpRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmOtpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *ConfirmOtpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfirmOtpRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ConfirmOtpRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ConfirmOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	TypeCustomer  string                 `protobuf:"bytes,2,opt,name=TypeCustomer,proto3" json:"TypeCustomer,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOtpResponse) Reset() {
	*x = ConfirmOtpResponse{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOtpResponse) ProtoMessage() {}

func (x *ConfirmOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOtpResponse.ProtoReflect.Descriptor instead.
func (*ConfirmOtpResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmOtpResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ConfirmOtpResponse) GetTypeCustomer() string {
	if x != nil {
		return x.TypeCustomer
	}
	return ""
}

func (x *ConfirmOtpResponse) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LoginUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LoginUserResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LoginUserResponse) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RefreshTokenResponse) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x0eshared.service\"V\n" +
	"\x10AuthServiceError\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x03R\aerrCode\x12'\n" +
	"\x0ferr_description\x18\x02 \x01(\tR\x0eerrDescription\",\n" +
	"\x14LoginCustomerRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"m\n" +
	"\x15LoginCustomerResponse\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\tR\trequestId\x126\n" +
	"\x05error\x18\x03 \x01(\v2 .shared.service.AuthServiceErrorR\x05error\".\n" +
	"\x0eSendOtpRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\"\x87\x01\n" +
	"\x0fSendOtpResponse\x12\x1e\n" +
	"\n" +
	"Expiration\x18\x01 \x01(\x05R\n" +
	"Expiration\x12\x1c\n" +
	"\tTotalSent\x18\x02 \x01(\x05R\tTotalSent\x126\n" +
	"\x05error\x18\x04 \x01(\v2 .shared.service.AuthServiceErrorR\x05error\"\x81\x01\n" +
	"\x11ConfirmOtpRequest\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\tR\x03otp\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"M\n" +
	"\x05Token\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\"\x9d\x01\n" +
	"\x12ConfirmOtpResponse\x12+\n" +
	"\x05Token\x18\x01 \x01(\v2\x15.shared.service.TokenR\x05Token\x12\"\n" +
	"\fTypeCustomer\x18\x02 \x01(\tR\fTypeCustomer\x126\n" +
	"\x05error\x18\x03 \x01(\v2 .shared.service.AuthServiceErrorR\x05error\"J\n" +
	"\x10LoginUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"i\n" +
	"\x11LoginUserResponse\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x126\n" +
	"\x05error\x18\x02 \x01(\v2 .shared.service.AuthServiceErrorR\x05error\"9\n" +
	"\x13RefreshTokenRequest\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"{\n" +
	"\x14RefreshTokenResponse\x12+\n" +
	"\x05token\x18\x01 \x01(\v2\x15.shared.service.TokenR\x05token\x126\n" +
	"\x05error\x18\x02 \x01(\v2 .shared.service.AuthServiceErrorR\x05error2\xb9\x03\n" +
	"\vAuthService\x12\\\n" +
	"\rLoginCustomer\x12$.shared.service.LoginCustomerRequest\x1a%.shared.service.LoginCustomerResponse\x12P\n" +
	"\tLoginUser\x12 .shared.service.LoginUserRequest\x1a!.shared.service.LoginUserResponse\x12J\n" +
	"\aSendOtp\x12\x1e.shared.service.SendOtpRequest\x1a\x1f.shared.service.SendOtpResponse\x12S\n" +
	"\n" +
	"ConfirmOtp\x12!.shared.service.ConfirmOtpRequest\x1a\".shared.service.ConfirmOtpResponse\x12Y\n" +
	"\fRefreshToken\x12#.shared.service.RefreshTokenRequest\x1a$.shared.service.RefreshTokenResponseB6Z4github.com/usmonnuriddinzoda/sharedpb/service/authpbb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_auth_proto_goTypes = []any{
	(*AuthServiceError)(nil),      // 0: shared.service.AuthServiceError
	(*LoginCustomerRequest)(nil),  // 1: shared.service.LoginCustomerRequest
	(*LoginCustomerResponse)(nil), // 2: shared.service.LoginCustomerResponse
	(*SendOtpRequest)(nil),        // 3: shared.service.SendOtpRequest
	(*SendOtpResponse)(nil),       // 4: shared.service.SendOtpResponse
	(*ConfirmOtpRequest)(nil),     // 5: shared.service.ConfirmOtpRequest
	(*Token)(nil),                 // 6: shared.service.Token
	(*ConfirmOtpResponse)(nil),    // 7: shared.service.ConfirmOtpResponse
	(*LoginUserRequest)(nil),      // 8: shared.service.LoginUserRequest
	(*LoginUserResponse)(nil),     // 9: shared.service.LoginUserResponse
	(*RefreshTokenRequest)(nil),   // 10: shared.service.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),  // 11: shared.service.RefreshTokenResponse
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: shared.service.LoginCustomerResponse.error:type_name -> shared.service.AuthServiceError
	0,  // 1: shared.service.SendOtpResponse.error:type_name -> shared.service.AuthServiceError
	6,  // 2: shared.service.ConfirmOtpResponse.Token:type_name -> shared.service.Token
	0,  // 3: shared.service.ConfirmOtpResponse.error:type_name -> shared.service.AuthServiceError
	0,  // 4: shared.service.LoginUserResponse.error:type_name -> shared.service.AuthServiceError
	6,  // 5: shared.service.RefreshTokenResponse.token:type_name -> shared.service.Token
	0,  // 6: shared.service.RefreshTokenResponse.error:type_name -> shared.service.AuthServiceError
	1,  // 7: shared.service.AuthService.LoginCustomer:input_type -> shared.service.LoginCustomerRequest
	8,  // 8: shared.service.AuthService.LoginUser:input_type -> shared.service.LoginUserRequest
	3,  // 9: shared.service.AuthService.SendOtp:input_type -> shared.service.SendOtpRequest
	5,  // 10: shared.service.AuthService.ConfirmOtp:input_type -> shared.service.ConfirmOtpRequest
	10, // 11: shared.service.AuthService.RefreshToken:input_type -> shared.service.RefreshTokenRequest
	2,  // 12: shared.service.AuthService.LoginCustomer:output_type -> shared.service.LoginCustomerResponse
	9,  // 13: shared.service.AuthService.LoginUser:output_type -> shared.service.LoginUserResponse
	4,  // 14: shared.service.AuthService.SendOtp:output_type -> shared.service.SendOtpResponse
	7,  // 15: shared.service.AuthService.ConfirmOtp:output_type -> shared.service.ConfirmOtpResponse
	11, // 16: shared.service.AuthService.RefreshToken:output_type -> shared.service.RefreshTokenResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
