// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthServiceError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ErrCode        int64                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrDescription string                 `protobuf:"bytes,2,opt,name=err_description,json=errDescription,proto3" json:"err_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthServiceError) Reset() {
	*x = AuthServiceError{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthServiceError) ProtoMessage() {}

func (x *AuthServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthServiceError.ProtoReflect.Descriptor instead.
func (*AuthServiceError) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthServiceError) GetErrCode() int64 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *AuthServiceError) GetErrDescription() string {
	if x != nil {
		return x.ErrDescription
	}
	return ""
}

type LoginCustomerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCustomerReq) Reset() {
	*x = LoginCustomerReq{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCustomerReq) ProtoMessage() {}

func (x *LoginCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCustomerReq.ProtoReflect.Descriptor instead.
func (*LoginCustomerReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginCustomerReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type LoginCustomerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCustomerResp) Reset() {
	*x = LoginCustomerResp{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCustomerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCustomerResp) ProtoMessage() {}

func (x *LoginCustomerResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCustomerResp.ProtoReflect.Descriptor instead.
func (*LoginCustomerResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginCustomerResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LoginCustomerResp) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type SendOtpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpReq) Reset() {
	*x = SendOtpReq{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpReq) ProtoMessage() {}

func (x *SendOtpReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpReq.ProtoReflect.Descriptor instead.
func (*SendOtpReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SendOtpReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SendOtpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expiration    int32                  `protobuf:"varint,1,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
	TotalSent     int32                  `protobuf:"varint,2,opt,name=TotalSent,proto3" json:"TotalSent,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpResp) Reset() {
	*x = SendOtpResp{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpResp) ProtoMessage() {}

func (x *SendOtpResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpResp.ProtoReflect.Descriptor instead.
func (*SendOtpResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SendOtpResp) GetExpiration() int32 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *SendOtpResp) GetTotalSent() int32 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *SendOtpResp) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ConfirmOtpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           string                 `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // IP клиента (если нужно фиксировать)
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"` // User-Agent клиента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOtpReq) Reset() {
	*x = ConfirmOtpReq{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOtpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOtpReq) ProtoMessage() {}

func (x *ConfirmOtpReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOtpReq.ProtoReflect.Descriptor instead.
func (*ConfirmOtpReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmOtpReq) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *ConfirmOtpReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfirmOtpReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ConfirmOtpReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ConfirmOtpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	TypeCustomer  string                 `protobuf:"bytes,2,opt,name=TypeCustomer,proto3" json:"TypeCustomer,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOtpResp) Reset() {
	*x = ConfirmOtpResp{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOtpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOtpResp) ProtoMessage() {}

func (x *ConfirmOtpResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOtpResp.ProtoReflect.Descriptor instead.
func (*ConfirmOtpResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmOtpResp) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ConfirmOtpResp) GetTypeCustomer() string {
	if x != nil {
		return x.TypeCustomer
	}
	return ""
}

func (x *ConfirmOtpResp) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type LoginUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserReq) Reset() {
	*x = LoginUserReq{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserReq) ProtoMessage() {}

func (x *LoginUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserReq.ProtoReflect.Descriptor instead.
func (*LoginUserReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LoginUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResp) Reset() {
	*x = LoginUserResp{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResp) ProtoMessage() {}

func (x *LoginUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResp.ProtoReflect.Descriptor instead.
func (*LoginUserResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LoginUserResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LoginUserResp) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         *AuthServiceError      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenResp) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RefreshTokenResp) GetError() *AuthServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x0eshared.service\"V\n" +
	"\x10AuthServiceError\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x03R\aerrCode\x12'\n" +
	"\x0ferr_description\x18\x02 \x01(\tR\x0eerrDescription\"(\n" +
	"\x10LoginCustomerReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"i\n" +
	"\x11LoginCustomerResp\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\tR\trequestId\x126\n" +
	"\x05error\x18\x03 \x01(\v2 .shared.service.AuthServiceErrorR\x05error\"*\n" +
	"\n" +
	"SendOtpReq\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\"\x83\x01\n" +
	"\vSendOtpResp\x12\x1e\n" +
	"\n" +
	"Expiration\x18\x01 \x01(\x05R\n" +
	"Expiration\x12\x1c\n" +
	"\tTotalSent\x18\x02 \x01(\x05R\tTotalSent\x126\n" +
	"\x05error\x18\x04 \x01(\v2 .shared.service.AuthServiceErrorR\x05error\"}\n" +
	"\rConfirmOtpReq\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\tR\x03otp\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"M\n" +
	"\x05Token\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\"\x99\x01\n" +
	"\x0eConfirmOtpResp\x12+\n" +
	"\x05Token\x18\x01 \x01(\v2\x15.shared.service.TokenR\x05Token\x12\"\n" +
	"\fTypeCustomer\x18\x02 \x01(\tR\fTypeCustomer\x126\n" +
	"\x05error\x18\x03 \x01(\v2 .shared.service.AuthServiceErrorR\x05error\"F\n" +
	"\fLoginUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"e\n" +
	"\rLoginUserResp\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x126\n" +
	"\x05error\x18\x02 \x01(\v2 .shared.service.AuthServiceErrorR\x05error\"5\n" +
	"\x0fRefreshTokenReq\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"w\n" +
	"\x10RefreshTokenResp\x12+\n" +
	"\x05token\x18\x01 \x01(\v2\x15.shared.service.TokenR\x05token\x126\n" +
	"\x05error\x18\x02 \x01(\v2 .shared.service.AuthServiceErrorR\x05error2\x91\x03\n" +
	"\vAuthService\x12T\n" +
	"\rLoginCustomer\x12 .shared.service.LoginCustomerReq\x1a!.shared.service.LoginCustomerResp\x12H\n" +
	"\tLoginUser\x12\x1c.shared.service.LoginUserReq\x1a\x1d.shared.service.LoginUserResp\x12B\n" +
	"\aSendOtp\x12\x1a.shared.service.SendOtpReq\x1a\x1b.shared.service.SendOtpResp\x12K\n" +
	"\n" +
	"ConfirmOtp\x12\x1d.shared.service.ConfirmOtpReq\x1a\x1e.shared.service.ConfirmOtpResp\x12Q\n" +
	"\fRefreshToken\x12\x1f.shared.service.RefreshTokenReq\x1a .shared.service.RefreshTokenRespB6Z4github.com/usmonnuriddinzoda/sharedpb/service/authpbb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_auth_proto_goTypes = []any{
	(*AuthServiceError)(nil),  // 0: shared.service.AuthServiceError
	(*LoginCustomerReq)(nil),  // 1: shared.service.LoginCustomerReq
	(*LoginCustomerResp)(nil), // 2: shared.service.LoginCustomerResp
	(*SendOtpReq)(nil),        // 3: shared.service.SendOtpReq
	(*SendOtpResp)(nil),       // 4: shared.service.SendOtpResp
	(*ConfirmOtpReq)(nil),     // 5: shared.service.ConfirmOtpReq
	(*Token)(nil),             // 6: shared.service.Token
	(*ConfirmOtpResp)(nil),    // 7: shared.service.ConfirmOtpResp
	(*LoginUserReq)(nil),      // 8: shared.service.LoginUserReq
	(*LoginUserResp)(nil),     // 9: shared.service.LoginUserResp
	(*RefreshTokenReq)(nil),   // 10: shared.service.RefreshTokenReq
	(*RefreshTokenResp)(nil),  // 11: shared.service.RefreshTokenResp
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: shared.service.LoginCustomerResp.error:type_name -> shared.service.AuthServiceError
	0,  // 1: shared.service.SendOtpResp.error:type_name -> shared.service.AuthServiceError
	6,  // 2: shared.service.ConfirmOtpResp.Token:type_name -> shared.service.Token
	0,  // 3: shared.service.ConfirmOtpResp.error:type_name -> shared.service.AuthServiceError
	0,  // 4: shared.service.LoginUserResp.error:type_name -> shared.service.AuthServiceError
	6,  // 5: shared.service.RefreshTokenResp.token:type_name -> shared.service.Token
	0,  // 6: shared.service.RefreshTokenResp.error:type_name -> shared.service.AuthServiceError
	1,  // 7: shared.service.AuthService.LoginCustomer:input_type -> shared.service.LoginCustomerReq
	8,  // 8: shared.service.AuthService.LoginUser:input_type -> shared.service.LoginUserReq
	3,  // 9: shared.service.AuthService.SendOtp:input_type -> shared.service.SendOtpReq
	5,  // 10: shared.service.AuthService.ConfirmOtp:input_type -> shared.service.ConfirmOtpReq
	10, // 11: shared.service.AuthService.RefreshToken:input_type -> shared.service.RefreshTokenReq
	2,  // 12: shared.service.AuthService.LoginCustomer:output_type -> shared.service.LoginCustomerResp
	9,  // 13: shared.service.AuthService.LoginUser:output_type -> shared.service.LoginUserResp
	4,  // 14: shared.service.AuthService.SendOtp:output_type -> shared.service.SendOtpResp
	7,  // 15: shared.service.AuthService.ConfirmOtp:output_type -> shared.service.ConfirmOtpResp
	11, // 16: shared.service.AuthService.RefreshToken:output_type -> shared.service.RefreshTokenResp
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
